export default [
  {
    name: 'Gif Convert',
    framework: 'Electron & React',
    description: 'Browser and desktop app to convert video to GIF.',
    year: '2021',
    liveLink: 'https://gifconvert.com/',
    githubLink: 'https://github.com/trybick/gifconvert',
  },
  {
    name: 'TV Minder',
    framework: 'React & Express',
    description: 'Full-stack application to track TV show schedules.',
    year: '2020',
    liveLink: 'https://tv-minder.com/',
    githubLink: 'https://github.com/trybick/tv-minder',
  },
  {
    name: 'Tray Tuner',
    framework: 'Electron',
    description: 'Desktop music application for online radio stations.',
    year: '2020',
    liveLink: 'https://traytuner.netlify.app/',
    githubLink: 'https://github.com/trybick/tray-tuner',
  },
  {
    name: 'Terminal Zoom',
    framework: 'TypeScript',
    description: `VSCode extension to control the terminal's font-size.`,
    year: '2019',
    liveLink: 'https://marketplace.visualstudio.com/items?itemName=trybick.terminal-zoom',
    githubLink: 'https://github.com/trybick/vscode-terminal-zoom',
  },
  {
    name: 'Issue Collab',
    framework: 'React',
    description: `Search tool for GitHub Issues inspired by Hacktoberfest.`,
    year: '2019',
    liveLink: 'https://issue-collab.dev/',
    githubLink: 'https://github.com/trybick/issue-collab',
  },
  {
    name: 'Slack Location Manager',
    framework: 'Node.js',
    description: `Automated command line tool which updates your Slack status based on location.`,
    year: '2019',
    liveLink: 'https://www.npmjs.com/package/slack-location-manager',
    githubLink: 'https://github.com/trybick/slack-location-manager',
  },
  {
    name: 'Sick Picks',
    framework: 'React & Node.js',
    description: `A compilation of recommendations from the hosts of a web development podcast.`,
    year: '2018',
    liveLink: 'https://sickpicks.netlify.com/',
    githubLink: 'https://github.com/trybick/sick-picks-scraper',
  },
];
